homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver

  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:
  
notify:
- name: ios_barrett_notify
  platform: ios
  target: !secret iphone_barrett_id
- name: ios_erica_notify
  platform: ios
  target: !secret iphone_erica_id

- name: iphones
  platform: group
  services:
  - service: ios_barretts_iphone
  - service: ios_ericas_iphone

ios:
  push:
    categories:
    - name: Lock
      identifier: LOCK
      actions:
      - identifier: LOCK_DOORS
        title: Lock Doors
        activationMode: background
        authenticationRequired: yes
        destructive: yes
        behavior: default
      - identifier: IGNORE
        title: Ignore
        activationMode: background
        authenticationRequired: no
        destructive: no
        behavior: default
    # - name: Alarm
    #   identifier: 'ALARM'
    #   actions:
    #   - identifier: 'SOUND_ALARM'
    #     title: 'Sound Alarm'
    #     activationMode: 'background'
    #     authenticationRequired: yes
    #     destructive: yes
    #     behavior: 'default'
    #   - identifier: 'SILENCE_ALARM'
    #     title: 'Silence Alarm'
    #     activationMode: 'background'
    #     authenticationRequired: yes
    #     destructive: no
    #     behavior: 'textInput'
    #     textInputButtonTitle: 'Silencio!'
    #     textInputPlaceholder: 'Placeholder'
    
    
# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: info
#   default: critical

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # ssl_certificate: /certs/fullchain.pem
  # ssl_key: /certs/privkey.pem
  
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
  
device_tracker:
- platform: netgear
  host: routerlogin.net
  username: !secret device_tracker_netgear_username
  password: !secret device_tracker_netgear_password
  port: 5000
  # Optional configuration

  # If new discovered devices are tracked by default (default: yes)
  track_new_devices: no
  # Seconds between each scan for new devices (default: 12)
  interval_seconds: 12
  # Seconds to wait till marking someone as not home after not being seen
  # (default: 180)
  consider_home: 180

# Use mosquitto
mqtt:
  broker: mqtt-broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

media_player:
- platform: kodi
  host: !secret raspberry_pie_ip
  name: ProtoPie
  username: !secret raspberry_pie_username
  password: !secret raspberry_pie_password
  turn_off_action: suspend
  
switch:
- platform: mqtt
  name: "Living Room"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Family Room"
  state_topic: "home/sonoff/family_room/1/stat"
  command_topic: "home/sonoff/family_room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Bedroom"
  state_topic: "home/sonoff/bedroom/1/stat"
  command_topic: "home/sonoff/bedroom/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true


camera:
- platform: synology
  url: !secret synology_url
  username: !secret synology_username
  password: !secret synology_password
  verify_ssl: False
  timeout: 20

- platform: local_file
  name: KSL Utah County Microcast
  file_path: /config/download/microProvo_new.jpg
- platform: local_file
  name: KSL Provo 7-day Forecast
  file_path: /config/download/7provo_new.jpg

binary_sensor:
- platform: template
  sensors:
    # barrett_iphone_is_home:
    #   value_template: "{%- is_state("device_tracker.barretts_iphone", "home") -%}"
    #   entity_id:
    #   - device_tracker.barretts_iphone
    # erica_iphone_is_home:
    #   value_template: "{%- is_state("device_tracker.ericas_iphone", "home") -%}"
    #   entity_id:
    #   - device_tracker.ericas_iphone
    home_secure:
      value_template: >-
        {%- if is_state("lock.back_deadbolt_locked", "unlocked")
        or is_state("lock.front_deadbolt_locked", "unlocked")
        or is_state("lock.garage_deadbolt_locked", "unlocked")
        or is_state("lock.kitchen_deadbolt_locked", "unlocked")
            -%}
        False
        {%- else -%}
        True
        {%- endif %}
      entity_id:
      - lock.back_door_lock_locked
      - lock.front_deadbolt_locked
      - lock.garage_deadbolt_locked
      - lock.kitchen_deadbolt_locked


# Weather prediction
sensor:
- platform: darksky
  api_key: !secret darksky_api_key
  name: ""
  monitored_conditions:
  - icon
  # - nearest_storm_distance
  # - nearest_storm_bearing
  - precip_type
  # - precip_intensity
  - precip_probability
  - temperature
  - apparent_temperature
  # - dew_point
  - wind_speed
  # - wind_bearing
  # - cloud_cover
  - humidity
  # - pressure
  # - visibility
  # - ozone
  - minutely_summary
  - hourly_summary
  - daily_summary
#  - platform: yr

# Text to speech
# tts:
# - platform: google
  
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: false # optional, default is false

shell_command:
  micro_provo: wget --continue --timestamping --directory-prefix=/config/download/ http://img.ksl.com/slc/weather/microProvo_new.jpg
  provo_7day: wget --continue --timestamping --directory-prefix=/config/download/ http://img.ksl.com/slc/weather/7provo_new.jpg
  # reboot: !secret reboot_command

zwave:
  device_config: !include zwave_device_config.yaml
  usb_path: /dev/ttyACM0
  

zone:
- name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 40
  icon: mdi:home

- name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 270
  icon: mdi:factory


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
